export const RETRIEVE_HUNT_LIST = 'RETRIEVE_HUNT_LIST';
export const RETRIEVE_USER_LOCATION = 'RETRIEVE_USER_LOCATION';
export const RETRIEVE_USER_INFO = 'RETRIEVE_USER_INFO';
export const LOGOUT_USER_INFO = 'LOGOUT_USER_INFO';


