# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'huntTest' do
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  
  pod 'GoogleMaps'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end

